language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '9'
  - '8'
  - '6'
  - '4'
script:
  - yarn
  # - yarn test:prod && yarn build # temporarly disabled because for some reason tslint doesn't work on travis
  - yarn test-types && yarn test -- --coverage --no-cache # tmp
after_success:
  - yarn report-coverage
  - yarn deploy-docs
  - yarn travis-deploy-once "yarn semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/