language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  # yarn: true
  npm: true
  directories:
    - node_modules
notifications:
  email: false
node_js: 8
script:
  - npm install # https://github.com/Microsoft/dtslint/issues/123
  # - yarn install --production=false
  - yarn test:prod
  - yarn build
after_success:
  - yarn report-coverage
  - yarn deploy-docs
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
