environment:
  nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

test_script:
  - node --version
  - yarn --version
  - yarn test:prod
  - yarn build

# Don't actually build.
build: off
